name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build


  generate_keymaps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          export PATH=$PATH:~/.local/bin  # Ensure pipx is in PATH
      - name: Install keymap-drawer using pipx
        run: |
          pipx install keymap-drawer  # Replace with the correct package name if different
      - name: Generate keymaps
        run: |
          for file in john_doe/*.json; do
            pipx run keymap-drawer -q 12 "$file"  # Use pipx to run the installed keymap-drawer
          done

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-generated keymap from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
